name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: WordPress Plugin Deploy
        uses: debba/action-wordpress-plugin-deploy@develop
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: two-factor-login-telegram
          ASSETS_DIR: .wordpress-org/assets
          README_DIR: .wordpress-org/readme
