name: Deploy to WordPress.org
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  build:
    name: Build plugin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install dependencies with Composer
        run: composer install --no-dev --optimize-autoloader

      - name: Install rsync (needed for act locally)
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Create plugin zip
        run: |
          PLUGIN_SLUG="two-factor-login-telegram"
          mkdir build
          rsync -av --exclude='.git*' --exclude='tests' --exclude='.*' ./ build/${PLUGIN_SLUG}/
          cd build
          zip -r "../${PLUGIN_SLUG}.zip" "${PLUGIN_SLUG}"
          cd ..

      - name: Upload artifact (for testing)
        uses: actions/upload-artifact@v4
        with:
          name: plugin-build
          path: authpress.zip

  deploy:
    name: Deploy to WordPress.org
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: WordPress Plugin Deploy
        uses: debba/action-wordpress-plugin-deploy@develop
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: two-factor-login-telegram
          ASSETS_DIR: .wordpress-org/assets
          README_DIR: .wordpress-org/readme
